CREATE DATABASE wad;

\c wad

CREATE USER wad WITH PASSWORD 'wad';
GRANT ALL PRIVILEGES ON DATABASE wad TO wad;

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  image_url VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
